import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/best-removebg.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from "../../public/images/profile/second-removebg-preview.png";
import TransitionEffect from '@/components/TransitionEffect';



export default function Home() {
  return (
    <>
      <Head>
        <title>Gulnur Mirzayeva</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="CodeGulnur" className='w-3/4 h-auto lg:hidden md:inline-block md:w-3/4 ml-14 mb-8'
                priority
                sizes="(max-width: 768px) 100vw,
  (max-width: 1200px) 50vw,
  50vw"
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Transforming Ideas Into Impactful Solutions Through Code and Design" className='!text-4xl !text-center
                xl:!text-3xl lg:!text-center lg:!text-5xl md:!text-4xl sm:!text-2xl'
              />
              <p className='my-4 text-center font-medium md:text-sm sm:text-xs'>
                As a passionate full-stack developer, I thrive on bringing visionary concepts to life with innovative web applications. My work reflects not just technical skill, but a dedication to excellence, creativity, and delivering real value. Explore my portfolio to see how I craft powerful, user-centric solutions that drive impact and success. Every line of code is a step toward building the future.
              </p>
              <div className='flex items-center self-center mt-2 lg:self-center'>
                <Link href="/Gulnur Mirzayeva.pdf" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base'
                  download={true}
                >Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link href="https://mail.google.com/mail/?view=cm&fs=1&to=gmirzyeva1@gmail.com" target={"_blank"}
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />


      </main>
    </>
  )
}
